# Generated by Django 2.2.19 on 2022-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220614_1517'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipes'), name='unique_user_recipes'),
        ),
    ]
